name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
      - ./.data:/.data
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_NOMBRE=MARTA
      - CLI_APELLIDO=PEREZ
      - CLI_DOCUMENTO=10234567
      - CLI_NACIMIENTO=1985-03-21
      - CLI_NUMERO=9876
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data:/.data

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24